global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "policy-service"
    static_configs:
      - targets: ["policy-service:8080"]
    metrics_path: /metrics

  - job_name: "calibration-service"
    static_configs:
      - targets: ["calibration-service:8081"]
    metrics_path: /metrics

  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: host.docker.internal:9100

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: /metrics
